apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-database
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  host: {{ .Values.database.host | quote }}
  port: {{ .Values.database.port | quote }}
  name: {{ .Values.database.database | quote }}
  user: {{ .Values.database.user | quote }}
  sslMode: {{ .Values.database.sslMode | quote }}
